export const user = {
  id: "clvn4uj2w0000w5392ka5tdci",
  name: "John Doe",
  email: "john.doe@gmail.com",
};

export const scores = [
  {
    points: 20,
    instrument: "guitar",
    tuning: "E Standard",
    timestamp: "2024-04-20T23:47:32.572Z",
    published: true,
    hardMode: false,
    username: "John Doe",
  },
  {
    points: 19,
    instrument: "guitar",
    tuning: "E Standard",
    timestamp: "2024-04-20T20:46:14.158Z",
    published: true,
    hardMode: false,
    username: "John Doe",
  },
  {
    points: 17,
    instrument: "bass",
    tuning: "E Standard",
    timestamp: "2024-04-20T20:54:07.200Z",
    published: true,
    hardMode: false,
    username: "John Doe",
  },
  {
    points: 15,
    instrument: "bass",
    tuning: "E Standard",
    timestamp: "2024-04-20T20:59:47.344Z",
    published: true,
    hardMode: false,
    username: "John Doe",
  },
  {
    points: 12,
    instrument: "guitar",
    tuning: "E Standard",
    timestamp: "2024-04-25T16:40:36.087Z",
    published: true,
    hardMode: true,
    username: "John Doe",
  },
  {
    points: 11,
    instrument: "guitar",
    tuning: "E Standard",
    timestamp: "2024-04-27T01:01:26.118Z",
    published: true,
    hardMode: true,
    username: "John Doe",
  },
  {
    points: 9,
    instrument: "guitar",
    tuning: "E Standard",
    timestamp: "2024-04-25T16:53:16.822Z",
    published: true,
    hardMode: true,
    username: "John Doe",
  },
  {
    points: 8,
    instrument: "guitar",
    tuning: "E Standard",
    timestamp: "2024-04-30T08:15:18.650Z",
    published: true,
    hardMode: true,
    username: "John Doe",
  },
  {
    points: 6,
    instrument: "ukulele",
    tuning: "Standard",
    timestamp: "2024-04-26T00:32:49.143Z",
    published: true,
    hardMode: true,
    username: "John Doe",
  },
];
